# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='cin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
