# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrow',
            name='date_borrow_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
